export const data = [
  {
    name: '-',
    level: 11,
    position: 'Senior Java разработчик, тех. лид',
    company: 'Сбер',
    city: 'Москва',
    type: 'Backend',
    skills: [
      'k8s',
      'openshift',
      'gradle',
      'maven',
      'jdbc',
      'sql',
      'hibernate',
      'spring',
      'jenkins',
      'ефс 20.1',
      'ппрб4',
      'dataspace',
      'platformV',
      'DevOpsTools',
      'java',
      'delphi',
      'bash',
      'git',
      'postgres',
      'firebird',
      'mysql'

    ],
    specs: [
      'ЕФС BH^',
      'ППРБ^',
      'CI/CD^',
      'Менеджмент',
    ],
    comments: ['2.5+ последних года разработка на платформах ЕФС и ППРБ', 'Люблю интересные задачи, люблю их больше чем не интересные', 'Сторонник agile', 'Знания в смежных областях (аналитика задач)']
  },
  {
    name: '-',
    level: 10,
    position: 'Senior (low) Главный инженер по тестированию',
    company: 'Сбер',
    city: 'Москва',
    type: 'QA',
    skills: [
      'SQL',
      'oracle',
      'postgress',
      'devtools',
      'postman',
      'kafka',
      'SOAP ui',
      'Kibana',
      'XML',
      'JSON',
      'REST',
      'Jenkins',
      'Teamcity',
      'DevOpsTools',
      'Google Analytics',
      'Yandex analytics',
      'Jmeter',

    ],
    specs: [
      'Нагрузочное тестирование^',
      'Интеграционное тестирование^',
      'Инциденты^',
      'ЕФС',
      'ППРБ',
    ],
  },
  {
    name: '-',
    level: 11,
    position: 'Senior Frontend developer, UI/UX лид',
    company: 'Корус',
    type: 'Frontend',
    city: 'Санкт-Петербург',
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'Redux',
      'Webpack',
      'ufs-ui',
      'v-uik',
      'MUI',
      'Node.js',
      'REST',
      'OpenApi',
      'Планирование',
      'Мониторинг',
      'Module Federation',
      'SystemJS',
      'Playwright',
      'Jest',
      'Allure'
    ],
    specs: [
      'UI/UX^',
      'ЕФС PL^',
      'Автотесты (Framework)^',
      'Frontend innersource',
      'ЕФС',
      'Монолит',
    ],
    comments: ['Cамоорганизованность и организация других', 'Знание смежных областей (дизайн / аналитика)', 'В свободное время ментор для 3х начинающих frontend-разработчиков', 'Ответственность за любой процесс и доведение процесса до результата', 'Склонность к планированию', 'Готовность к любым сторонним активностям']
  },
  {
    name: '-',
    level: 11,
    position: 'Senior Frontend developer, Release Team лид (ВРИО ВП, STL, ЛАС)',
    company: 'Сбер',
    type: 'Team Lead',
    city: 'Москва',
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'Redux',
      'Webpack',
      'ufs-ui',
      'v-uik',
      'MUI',
      'Node.js',
      'REST',
      'OpenApi',
      'Планирование',
      'Мониторинг',
      'Module Federation',
      'SystemJS',
      'Playwright',
      'Jest',
      'Allure',
      'SberWorks',
      'Черная Jira',
      'PlantUML',
      'OpenApi',
      'Sowa',
      'Nginx',
    ],
    specs: [
      'Release Team^',
      'ЕФС PL',
      'Frontend innersource',
      'ЕФС',
      'Монолит',
    ],
      comments: ['Частично исполнян обязанности ВП/STL/Лидера 3х АС.', 'Опыт работы в банке - 6 лет.','Опыт в руководстве (15 человек) - 2 года.', 'Опыт работы в 3х трайбах. ', '2 грамоты от руководства.', 'Разработка внутренних инструментов мониторинга/планирования/производственных метрик.', 'Краткосрочное и долгосрочное планирование.', 'При большой загрузке специалистов исполняю функции аналитика.', 'Внедряю Best-practices.', 'Менторю коллег.']
  },
  {
    name: '-',
    level: 9,
    position: 'Middle Java разработчик',
    city: 'Москва',
    type: 'Backend',
    company: 'Корус',
    skills: [
      'Java',
      'Spring',
      'Hibernate',
      'WebFlux',
      'Kubernetes',
      'OpenShift',
      'Istio'
    ],
    specs: [
      'Unit тесты^',
      'ЕФС BH',
      'OSE',
      'Автономность',
    ],
    comments: ['Настройка open shift, istio', 'Соло бэкэнд разработка и вывод в ПРОМ сервиса (в рамках перехода на новую архитектуру)']
  },
  {
    name: '-',
    level: 9,
    position: 'Middle QA Manual, Junior+ Qa Automation',
    company: 'Сбер',
    type: 'QA',
    city: 'Москва',
    skills: [
      'JavaScript',
      'Black Box testing',
      'BDD',
      'Agile',
      'Jira',
      'git',
      'Selenium',
      'CSS'
    ],
    specs: [
      'Ручное тестирование^',
      'BDD автотесты^',
      'Scrum master',
      'ЕФС',
    ],
    comments: ['Тестирование пользовательского пути', 'Работа с тестовой моделью', 'Тестовые прогоны', 'Ведение jira', 'Практический опыт работы по Agile (scrum /kanban) спринты 1-2 недели', 'Работа с дефектами', 'Обеспечение настроек организации на стендах ift/psi']
  },
  {
    name: '-',
    level: 9,
    position: 'Инженер IT сопровождения/junior Devops',
    type: 'DevOps',
    company: 'Сбер',
    city: 'Москва',
    skills: [
      'ЗНОопс',
      'Работа в Service Manager',
      'Настройка/Сопровождение тестовых стендов',
      'Настройка/Сопровождение CI/CD pipeline',
      'Устранение рисков',
      'Администрирование Unix КТС',
      'Сопровождение проектов OSE',
      'Groovy',
      'Ansible'
    ],
    specs: [
      'Администрирование стендов^',
      'Delivery^',
      'Разработка Job-ов',
      'ЕФС',
      'ППРБ'
    ],
    comments: ['Сопровождение Job-ов CI/CD команды', 'Администрирование стендов DEV/IFT/NT команды по 3м проектам (~50 КТС)', 'Работа с сопровождением ПСИ/ПРОМ']
  },
  {
    name: '-',
    level: 7,
    position: 'Junior+ Java разработчик',
    type: 'Backend',
    city: 'Москва',
    company: 'Сбер',
    skills: [
      'Java',
      'Gradle',
      'Maven',
      'PostgreSQL',
      'Kubernetes',
      'Hubernate ORM',
      'Spring',
      'Junit',
      'Mockito',
      'Docker'
    ],
    specs: [
      'ЕФС BH',
      'ППРБ',
      'OSE'
    ]
  },
  {
    name: '-',
    level: 11,
    position: 'Middle+ Системный аналитик',
    city: 'Москва',
    type: 'Analyst',
    company: 'Сбер',
    skills: [
      'GIT',
      'PlantUML (UML)',
      'BPMN 2.0',
      'C',
      'openAPI',
      'SQL',
      'PowerShell',
      'Java'
    ],
    specs: [
      'ЕФС',
      'ППРБ',
      'Системная аналитика',
      'OpenApi'
    ]
  },
];
